<a href="https://colab.research.google.com/github/KirillSmirnov2/InnopolisStudentPublicRepository/blob/main/HW4_SmirnovKK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Домашнее задание

Для работы можно использовать тот же датасет, что и в прошлом домашнем задании, если он содержит в себе пропуски.

В противном случае следует выбрать подходящий датасет на сайте Kaggle: https://www.kaggle.com/.

Выполнить следующие задачи:

- 1 поиск и удаление дубликатов;

- 2 разделить таблицу на две новых, и объединить их разными способами;

- 3 выполнить нормализацию численных данных;

- 4 определить процент пропусков, удалить их или заменить. Решение обосновать.

== ==================================================== ==

In [35]:
# @title Загружен иной по сравнению с прошлыми ДЗ датасет
import pandas as pd
df=pd.read_csv('healthcare-dataset-stroke-data.csv')

In [36]:
# @title Запрос описания датасета 'healthcare-dataset-stroke-data.csv'
#print(df)
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5110.000000,5110.000000,5110.000000,5110.000000,5110.000000,4909.000000,5110.000000
mean,36517.829354,43.226614,0.097456,0.054012,106.147677,28.893237,0.048728
std,21161.721625,22.612647,0.296607,0.226063,45.283560,7.854067,0.215320
min,67.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,17741.250000,25.000000,0.000000,0.000000,77.245000,23.500000,0.000000
50%,36932.000000,45.000000,0.000000,0.000000,91.885000,28.100000,0.000000
75%,54682.000000,61.000000,0.000000,0.000000,114.090000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000

В датасете есть незаполненные строки (201 шт)

In [37]:
df['bmi']

0       36.6
1        NaN
2       32.5
3       34.4
4       24.0
        ...
5105     NaN
5106    40.0
5107    30.6
5108    25.6
5109    26.2
Name: bmi, Length: 5110, dtype: float64

Не везде заполнен индекс массы тела bmi

In [38]:
df.isnull().describe()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
count,5110,5110,5110,5110,5110,5110,5110,5110,5110,5110,5110,5110
unique,1,1,1,1,1,1,1,1,1,2,1,1
top,False,False,False,False,False,False,False,False,False,False,False,False
freq,5110,5110,5110,5110,5110,5110,5110,5110,5110,4909,5110,5110

== ==================================================== ==

Задача 1  поиск и удаление дубликатов;

== ==================================================== ==

In [39]:
df.loc[df.duplicated() == True]

Empty DataFrame
Columns: [id, gender, age, hypertension, heart_disease, ever_married, work_type, Residence_type, avg_glucose_level, bmi, smoking_status, stroke]
Index: []

Отсутствуют дубликаты полных строк данных

In [40]:
df.loc[df.duplicated(subset =['id']) == True]

Empty DataFrame
Columns: [id, gender, age, hypertension, heart_disease, ever_married, work_type, Residence_type, avg_glucose_level, bmi, smoking_status, stroke]
Index: []

id уникальны !

== ==================================================== ==

2 разделить таблицу на две новых, и объединить их разными способами;

== ==================================================== ==

In [41]:
# @title выпишем имеющиеся отметки в столбцах [gender], [ever_married], [work_type], [Residence_type], [smoking_status]
print('gender data: ',set(df['gender'].tolist()))
print('marriage data(ever_married): ',set(df['ever_married'].tolist()))
print('work_type data: ',set(df['work_type'].tolist()))
print('Residence_type: ',set(df['Residence_type'].tolist()))
print('smoking_status data: ',set(df['smoking_status'].tolist()))

gender data:  {'Other', 'Male', 'Female'}
marriage data(ever_married):  {'No', 'Yes'}
work_type data:  {'children', 'Self-employed', 'Private', 'Govt_job', 'Never_worked'}
Residence_type:  {'Urban', 'Rural'}
smoking_status data:  {'never smoked', 'smokes', 'formerly smoked', 'Unknown'}

In [77]:
# @title 2 разделить таблицу на две новых, и объединить их разными способами; --concat--
df1=df.copy(deep=True)

#df1=df1.iloc[(df1['Residence_type'] == Urban).index]
df1_Urban=df1.iloc[df1.loc[df['Residence_type'] == 'Urban'].index]
df1_Rural=df1.iloc[list(set(df1.index)-set(LIU))]
df1_Urban=df1_Urban.drop('Residence_type', axis=1)
df1_Rural=df1_Rural.drop('Residence_type', axis=1)

#print(df1_Urban)
#print(df1_Rural)
#df2=pd.concat([df1_Urban, df1_Rural], axis=1)
df2=pd.concat([df1_Urban, df1_Rural],  keys = ['Urban', 'Rural'])
print('== ==================================================== ==')
print(df2)
df2.info()

== ==================================================== ==
               id  gender   age  hypertension  heart_disease ever_married  \
Urban 0      9046    Male  67.0             0              1          Yes
      3     60182  Female  49.0             0              0          Yes
      5     56669    Male  81.0             0              0          Yes
      7     10434  Female  69.0             0              0           No
      9     60491  Female  78.0             0              0          Yes
...           ...     ...   ...           ...            ...          ...
Rural 5100  68398    Male  82.0             1              0          Yes
      5102  45010  Female  57.0             0              0          Yes
      5104  14180  Female  13.0             0              0           No
      5107  19723  Female  35.0             0              0          Yes
      5108  37544    Male  51.0             0              0          Yes

                work_type  avg_glucose_level   bmi   smoking_status  stroke
Urban 0           Private             228.69  36.6  formerly smoked       1
      3           Private             171.23  34.4           smokes       1
      5           Private             186.21  29.0  formerly smoked       1
      7           Private              94.39  22.8     never smoked       1
      9           Private              58.57  24.2          Unknown       1
...                   ...                ...   ...              ...     ...
Rural 5100  Self-employed              71.97  28.3     never smoked       0
      5102        Private              77.93  21.7     never smoked       0
      5104       children             103.08  18.6          Unknown       0
      5107  Self-employed              82.99  30.6     never smoked       0
      5108        Private             166.29  25.6  formerly smoked       0

[5110 rows x 11 columns]
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5110 entries, ('Urban', 0) to ('Rural', 5108)
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   avg_glucose_level  5110 non-null   float64
 8   bmi                4909 non-null   float64
 9   smoking_status     5110 non-null   object
 10  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(4)
memory usage: 623.2+ KB

Dataframe разделен на два - по месту жительства пациентов - городские[Urban] и сельские[Rural]  и объеденены потом методом concat  с ключом по месту жительства

In [160]:
# @title 2 разделить таблицу на две новых, и объединить их разными способами; --merge--
df3=df.copy(deep=True)
df4=df.copy(deep=True)

TS=set(df.columns.values.tolist())
print(TS)
print('== ==================================================== ==')

Lis_1=['gender', 'ever_married','work_type','Residence_type','smoking_status']
set_1=set(Lis_1)
set_2=TS - set_1

set_2_1=set_2-{'id'}
Lis_2=list(set_2_1)

print(Lis_1)
print(Lis_2)
#Lis_1x=
#Lis_2x=


df3=df3.drop(Lis_1, axis= 1 , inplace= False )
df4=df4.drop(Lis_2, axis= 1 , inplace= False )

print('\n','df3__________________','\n',df3.columns.values.tolist(),'  ' ,len(df3))
print('\n','df4__________________','\n',df4.columns.values.tolist(),'  ' ,len(df4))

print('== ==================================================== ==')
df3.info()
print('== ==================================================== ==')
df4.info()
print('== ==================================================== ==')


Fix_list=df3.loc[(df3.isna())['bmi'] == False].index
print(len(Fix1))
df3_Fix=df3.iloc[Fix_list]
df4_Fix=df4.iloc[Fix_list]
df5= pd.merge(df3_Fix, df4_Fix, on='id', how='outer')
print('== ============   merged dataframe ================================ ==')
df5.info()

{'hypertension', 'Residence_type', 'id', 'gender', 'work_type', 'smoking_status', 'bmi', 'ever_married', 'age', 'stroke', 'heart_disease', 'avg_glucose_level'}
== ==================================================== ==
['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status']
['hypertension', 'stroke', 'bmi', 'age', 'heart_disease', 'avg_glucose_level']

 df3__________________
 ['id', 'age', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi', 'stroke']    5110

 df4__________________
 ['id', 'gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status']    5110
== ==================================================== ==
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   age                5110 non-null   float64
 2   hypertension       5110 non-null   int64
 3   heart_disease      5110 non-null   int64
 4   avg_glucose_level  5110 non-null   float64
 5   bmi                4909 non-null   float64
 6   stroke             5110 non-null   int64
dtypes: float64(3), int64(4)
memory usage: 279.6 KB
== ==================================================== ==
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              5110 non-null   int64
 1   gender          5110 non-null   object
 2   ever_married    5110 non-null   object
 3   work_type       5110 non-null   object
 4   Residence_type  5110 non-null   object
 5   smoking_status  5110 non-null   object
dtypes: int64(1), object(5)
memory usage: 239.7+ KB
== ==================================================== ==
201
== ============   merged dataframe ================================ ==
<class 'pandas.core.frame.DataFrame'>
Int64Index: 4909 entries, 0 to 4908
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 4909 non-null   int64
 1   age                4909 non-null   float64
 2   hypertension       4909 non-null   int64
 3   heart_disease      4909 non-null   int64
 4   avg_glucose_level  4909 non-null   float64
 5   bmi                4909 non-null   float64
 6   stroke             4909 non-null   int64
 7   gender             4909 non-null   object
 8   ever_married       4909 non-null   object
 9   work_type          4909 non-null   object
 10  Residence_type     4909 non-null   object
 11  smoking_status     4909 non-null   object
dtypes: float64(3), int64(4), object(5)
memory usage: 498.6+ KB

Dataframe разделены по столбцам, определены стриоки  [bmi] NaN, соединены merge в одну dataframe

In [188]:
# @title 3 выполнить нормализацию численных данных;
#print(df3_Fix)
from sklearn.preprocessing import normalize
N1=normalize(df3_Fix, norm='max', axis=1)
print(N1)
print(len(N1))

[[1.00000000e+00 7.40658855e-03 0.00000000e+00 ... 2.52807871e-02
  4.04598718e-03 1.10546098e-04]
 [1.00000000e+00 2.57135510e-03 0.00000000e+00 ... 3.40447416e-03
  1.04461301e-03 3.21419388e-05]
 [1.00000000e+00 8.14196936e-04 0.00000000e+00 ... 2.84520288e-03
  5.71599482e-04 1.66162640e-05]
 ...
 [1.00000000e+00 1.77457790e-03 0.00000000e+00 ... 4.20777772e-03
  1.55148811e-03 0.00000000e+00]
 [1.00000000e+00 1.35840614e-03 0.00000000e+00 ... 4.42920307e-03
  6.81866610e-04 0.00000000e+00]
 [1.00000000e+00 9.84802704e-04 0.00000000e+00 ... 1.90872669e-03
  5.86405246e-04 0.00000000e+00]]
4909

In [192]:
# @title 4 определить процент пропусков, удалить их или заменить. Решение обосновать.
df.info()
print('== ==================================================== ==')
df_propusk=len(df.loc[df.isna()['bmi'] == True])
df_all=len(df)
if df_all>0:
  proc= df_propusk / df_all *100
else:
  pass
print(f'Процент пропусков {proc:.4f} %')
print('== ==================================================== ==')
if proc < 5:
  print('== Можно удалить строки ==')
else:
  print('== Рекомендуется доп.анализ и заполнить ==')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB
== ==================================================== ==
Процент пропусков 3.9335 %
== ==================================================== ==
== Можно удалить строки ==

In [194]:
# @title Поскольку можно удалить строки, то можно использовать ранее определенные dataframe с уже выполненными операциями.
print(df5)
df5.describe()

         id   age  hypertension  heart_disease  avg_glucose_level   bmi  \
0      9046  67.0             0              1             228.69  36.6
1     31112  80.0             0              1             105.92  32.5
2     60182  49.0             0              0             171.23  34.4
3      1665  79.0             1              0             174.12  24.0
4     56669  81.0             0              0             186.21  29.0
...     ...   ...           ...            ...                ...   ...
4904  14180  13.0             0              0             103.08  18.6
4905  44873  81.0             0              0             125.20  40.0
4906  19723  35.0             0              0              82.99  30.6
4907  37544  51.0             0              0             166.29  25.6
4908  44679  44.0             0              0              85.28  26.2

      stroke  gender ever_married      work_type Residence_type  \
0          1    Male          Yes        Private          Urban
1          1    Male          Yes        Private          Rural
2          1  Female          Yes        Private          Urban
3          1  Female          Yes  Self-employed          Rural
4          1    Male          Yes        Private          Urban
...      ...     ...          ...            ...            ...
4904       0  Female           No       children          Rural
4905       0  Female          Yes  Self-employed          Urban
4906       0  Female          Yes  Self-employed          Rural
4907       0    Male          Yes        Private          Rural
4908       0  Female          Yes       Govt_job          Urban

       smoking_status
0     formerly smoked
1        never smoked
2              smokes
3        never smoked
4     formerly smoked
...               ...
4904          Unknown
4905     never smoked
4906     never smoked
4907  formerly smoked
4908          Unknown

[4909 rows x 12 columns]

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,4909.000000,4909.000000,4909.000000,4909.000000,4909.000000,4909.000000,4909.000000
mean,37064.313506,42.865374,0.091872,0.049501,105.305150,28.893237,0.042575
std,20995.098457,22.555115,0.288875,0.216934,44.424341,7.854067,0.201917
min,77.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,18605.000000,25.000000,0.000000,0.000000,77.070000,23.500000,0.000000
50%,37608.000000,44.000000,0.000000,0.000000,91.680000,28.100000,0.000000
75%,55220.000000,60.000000,0.000000,0.000000,113.570000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000